server:
  port: 8081

spring:
  application:
    name: DOMAIN-FETCHER-SERVICE-APPLICATION

domain:
  topic:
    name: web-domains
  api:
    base-url: https://api.domainsdb.info/v1/domains/search?domain