server:
  port: 8083

spring:
  application:
    name: DOMAIN-PERSISTING-SERVICE-APPLICATION
  datasource:
    url: jdbc:mysql://localhost:3306/web_domains
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    stream:
      function:
        definition: kafkaDomainInformationConsumer
      bindings:
         kafkaDomainInformationConsumer-in-0:
           destination: active-web-domains
      kafka:
        binder:
          - localhost:9091
          - localhost:9092
        bindings:
          kafkaDomainInformationConsumer-in-0:
            consumer:
              configuration:
                value:
                  deserializer: org.springframweork.kafka.support.serializer.JsonDeserializer





