server:
  port: 8082

spring:
  application:
    name: DOMAIN-PROCESSOR-SERVICE-APPLICATION
  cloud:
    stream:
      function:
        definition: kafkaDomainProcessor
      bindings:
        kafkaDomainProcessor-in-0:
          destination: web-domains
        kafkaDomainProcessor-out-0:
          destination: active-web-domains
      kafka:
        binder:
          brokers:
            - localhost:9091
            - localhost:9092
        bindings:
          kafkaDomainProcessor-in-0:
            consumer:
              configuration:
                value:
                  deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          kafkaDomainProcessor-out-0:
            producer:
              configuration:
                value:
                  serializer: org.springframework.kafka.support.serializer.JsonSerializer
